### ISSUE TITLE
Downloads link is broken

### ISSUE THREAD

**Issue by vanishakesswani** [pulkomandy/critical-mass#6]
The downloads link on https://github.com/pulkomandy/critical-mass gives me a 404 error .
![critical mass](https://cloud.githubusercontent.com/assets/24365311/21418215/aea13a20-c845-11e6-8c40-ffdcf2f76917.PNG)

**Comment by pulkomandy** [comment]
Ah yes, HaikuWare does not exist anymore. thanks for reporting!
