### ISSUE TITLE
Incorrect SOURCE_FILENAME in criticalmass-2.2.recipe

### ISSUE THREAD

**Issue by vanishakesswani** [pulkomandy/critical-mass#8]
![recipe_incorrect](https://cloud.githubusercontent.com/assets/24365311/21423887/6bab2c2e-c865-11e6-869e-9dcad8e829bb.png)
If you have a look at SOURCE_FILENAME in the recipe file you realize that it is incorrect .

**Comment by pulkomandy** [comment]
This problem should be reported on HaikuPorts side (a pull request would be even better!).

**Comment by vanishakesswani** [comment]
https://github.com/haikuports/haikuports/pull/944
